### ISSUE TITLE
[Announce] stitchES-Vue

### ISSUE THREAD

**Issue by glassworm** [sudara/stitchES#69]
Instead of debugging some old code borrowing heavily from an early verison of StitchES, I decided first to implement a Vue.js component using latest ```master``` here for inspiration:

https://github.com/glassworm/stitchES-Vue

Now that I am refreshed on how all this fits together I'm going to try to integrate what is now cleaner and better code into my own project.

Thanks again for stitchES, @sudara!

**Comment by sudara** [comment]
Cool, we were recently discussing how stitches might work as React components...

If you have any ideas on how stitches itself could better support Vue, let me know, I'm open to it. It doesn't seem sustainable to have the code copy and pasted (you won't get any bugfixes etc)

**Comment by glassworm** [comment]
Right and understood, I don't think there are any paths forward that are straight wrt maintaining 2 repos and this was mostly just an exercise so others could see as an example.  That you've decided to codify a decade of frustration over browser audio headaches is of general benefit when it comes to helping us in frameworks like Vue that lack in this area.
